version: '3.8'

services:
  db:
    image: postgres:17
    container_name: quester-db
    ports:
      - 5555:5432
    volumes:
      - quester_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  quester_pgdata:
